---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmqs-0
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /rabbitmqstatefulset/rabbitmq0/
    server: 172.16.231.182
    
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmqs-1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /rabbitmqstatefulset/rabbitmq1/
    server: 172.16.231.182
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmqs-2
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /rabbitmqstatefulset/rabbitmq2/
    server: 172.16.231.182

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-rabbitmqs-0
  namespace: vems
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: rabbitmqs-0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-rabbitmqs-1
  namespace: vems
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: rabbitmqs-1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-rabbitmqs-2
  namespace: vems
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: rabbitmqs-2

